# Example configuration for built-in plugins
server:
  port: 8080
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s

logging:
  level: info
  format: json

# Built-in plugins configuration
plugins:
  # Authentication Plugin - JWT and API Key authentication
  - name: auth
    enabled: true
    config:
      # JWT Configuration
      jwt_secret: "your-super-secret-jwt-key-change-this-in-production"
      jwt_method: "HS256"  # HS256, HS384, HS512, RS256, RS384, RS512
      jwt_issuer: "vanta-mocker"
      jwt_audience: "api-users"
      
      # API Key Configuration
      api_keys:
        "api-key-admin-123": "admin-user"
        "api-key-user-456": "regular-user"
        "api-key-readonly-789": "readonly-user"
      
      # Authentication sources
      auth_header: "Authorization"
      auth_query: "api_key"
      auth_cookie: "auth_token"
      
      # Public endpoints (no authentication required)
      public_endpoints:
        - "/health"
        - "/metrics"
        - "/docs"
        - "/openapi.yaml"

  # Rate Limiting Plugin - Sliding window rate limiting
  - name: rate_limit
    enabled: true
    config:
      # Global rate limiting (across all requests)
      global_requests_per_second: 1000.0
      global_burst: 2000
      
      # Per-IP rate limiting
      ip_requests_per_second: 100.0
      ip_burst: 200
      
      # Per-user rate limiting (for authenticated users)
      user_requests_per_second: 50.0
      user_burst: 100
      
      # Exempt IPs (no rate limiting applied)
      exempt_ips:
        - "127.0.0.1"
        - "::1"
        - "10.0.0.0/8"     # Private networks
        - "172.16.0.0/12"
        - "192.168.0.0/16"
      
      # Cleanup configuration
      cleanup_interval_seconds: 300  # 5 minutes
      entry_ttl_seconds: 1800        # 30 minutes

  # CORS Plugin - Enhanced CORS management
  - name: cors
    enabled: true
    config:
      # Allowed origins
      allow_origins:
        - "http://localhost:3000"
        - "http://localhost:3001"
        - "https://yourdomain.com"
        - "https://*.yourdomain.com"
      
      # Alternative: Use origin patterns for dynamic validation
      origin_patterns:
        - "^https://[a-zA-Z0-9-]+\\.yourdomain\\.com$"
        - "^http://localhost:[0-9]+$"
      
      # Allowed HTTP methods
      allow_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
        - "PATCH"
        - "OPTIONS"
        - "HEAD"
      
      # Allowed headers
      allow_headers:
        - "Origin"
        - "Content-Type"
        - "Accept"
        - "Authorization"
        - "X-Requested-With"
        - "X-API-Key"
        - "X-Client-Version"
      
      # Headers to expose to the client
      expose_headers:
        - "X-Total-Count"
        - "X-Rate-Limit-Remaining"
        - "X-Rate-Limit-Reset"
      
      # Allow credentials (cookies, authorization headers)
      allow_credentials: true
      
      # Preflight cache duration (seconds)
      max_age: 86400  # 24 hours

  # Logging Plugin - Structured request/response logging
  - name: logging
    enabled: true
    config:
      # Log level for plugin (debug, info, warn, error)
      log_level: "info"
      
      # Body logging configuration
      log_request_body: true
      log_response_body: true
      max_body_size: 65536  # 64KB max body size to log
      
      # Sensitive data filtering
      sensitive_headers:
        - "authorization"
        - "cookie"
        - "x-api-key"
        - "x-auth-token"
        - "x-secret-key"
      
      sensitive_fields:
        - "password"
        - "secret"
        - "token"
        - "key"
        - "credential"
        - "auth"
        - "session"
      
      # Log format and metrics
      log_format: "json"  # json or console
      include_metrics: true